Fix tab

diff --git a/src/bin/rrh-cat-output b/src/bin/rrh-cat-output
--- a/src/bin/rrh-cat-output
+++ b/src/bin/rrh-cat-output
@@ -6,25 +6,25 @@ RRH_USR_BIN="."
 RRH_VAR="$HOME/.cache/rrh-test"
 
 if [ $# -gt 1 ]; then
-	echo "Usage: rrh-cat-output [ACTION_ID]"
-	echo "Print the output of action."
-	echo "RRH $RRH_VERSION"
-	exit 8
+    echo "Usage: rrh-cat-output [ACTION_ID]"
+    echo "Print the output of action."
+    echo "RRH $RRH_VERSION"
+    exit 8
 fi
 
 if [ $# -eq 0 ]; then
-	ACTION_ID="$(cat $RRH_VAR/last)"
-	if [ ! $? -eq 0 ]; then
-		echo "read last action id failed!"
-		exit 9
-	fi
+    ACTION_ID="$(cat $RRH_VAR/last)"
+    if [ ! $? -eq 0 ]; then
+        echo "read last action id failed!"
+        exit 9
+    fi
 else
-	ACTION_ID="$1"
+    ACTION_ID="$1"
 fi
 
 if [ ! -d "$RRH_VAR/action/$ACTION_ID" ]; then
-	echo "action(id $ACTION_ID) not exists!"
-	exit 10
+    echo "action(id $ACTION_ID) not exists!"
+    exit 10
 fi
 
 cat "$RRH_VAR/action/$ACTION_ID/cmd_output"
diff --git a/src/bin/rrh-full-update b/src/bin/rrh-full-update
--- a/src/bin/rrh-full-update
+++ b/src/bin/rrh-full-update
@@ -6,28 +6,28 @@ RRH_USR_BIN="."
 RRH_VAR="$HOME/.cache/rrh-test"
 
 if [ "$(id -un)" != "root" ]; then
-	"$RRH_USR_BIN/rrh-doas" "root" "$0" "$@"
-	exit $?
+    "$RRH_USR_BIN/rrh-doas" "root" "$0" "$@"
+    exit $?
 fi
-	
+    
 if [ ! -f "/etc/rrh/cmd/update" ]; then
-	echo "/etc/rrh/cmd/update not exists!" >&2
-	exit 1
+    echo "/etc/rrh/cmd/update not exists!" >&2
+    exit 1
 fi
 
 CONFIG_USER="root"
 if [ -f "/etc/rrh/user" ]; then
-	CONFIG_USER="$(cat /etc/rrh/user)"
-	if [ ! $? -eq 0 ]; then
-		echo "read user config failed!" >&2
-		exit 2
-	fi
+    CONFIG_USER="$(cat /etc/rrh/user)"
+    if [ ! $? -eq 0 ]; then
+        echo "read user config failed!" >&2
+        exit 2
+    fi
 fi
 
 ACTION_ID=$(date -u +'%Y%m%d%H%M%S')
 if [ ! $? -eq 0 ]; then
-	echo "generate action id failed!" >&2
-	exit 3
+    echo "generate action id failed!" >&2
+    exit 3
 fi
 CMD_OUTPUT_FILE="$RRH_VAR/action/$ACTION_ID/cmd_output"
 EXIT_CODE_FILE="$RRH_VAR/action/$ACTION_ID/exit_code"
@@ -35,97 +35,97 @@ EXIT_CODE_FILE="$RRH_VAR/action/$ACTION_ID/exit_code"
 exec 200>/run/rrh.lck
 flock -nxE 1 200
 if [ ! $? -eq 0 ]; then
-	echo "get lock failed!" >&2
-	exit 5
+    echo "get lock failed!" >&2
+    exit 5
 fi
 
 if [ -f /etc/rrh/cmd/pre_update ]; then
-	/etc/rrh/cmd/pre_update
-	PRE_UPDATE_CODE=$?
-	if [ ! $PRE_UPDATE_CODE -eq 0 ]; then
-		echo "pre_update cmd failed(code $PRE_UPDATE_CODE)!"
-		exec 200>&-
-		rm /run/rrh.lck
-		exit 14
-	fi
+    /etc/rrh/cmd/pre_update
+    PRE_UPDATE_CODE=$?
+    if [ ! $PRE_UPDATE_CODE -eq 0 ]; then
+        echo "pre_update cmd failed(code $PRE_UPDATE_CODE)!"
+        exec 200>&-
+        rm /run/rrh.lck
+        exit 14
+    fi
 fi
 
 mkdir -p "$RRH_VAR/action/${ACTION_ID}"
 if [ ! $? -eq 0 ]; then
-	echo "create action dir failed!" >&2
-	exec 200>&-
-	rm /run/rrh.lck
-	exit 4
+    echo "create action dir failed!" >&2
+    exec 200>&-
+    rm /run/rrh.lck
+    exit 4
 fi
 
 if command -v "unbuffer" >/dev/null 2>&1; then
-	"$RRH_USR_BIN/rrh-doas" "$CONFIG_USER" unbuffer /etc/rrh/cmd/update "$@" 2>&1 | tee "$CMD_OUTPUT_FILE"
-	UPDATE_EXIT_CODE=$?
+    "$RRH_USR_BIN/rrh-doas" "$CONFIG_USER" unbuffer /etc/rrh/cmd/update "$@" 2>&1 | tee "$CMD_OUTPUT_FILE"
+    UPDATE_EXIT_CODE=$?
 else
-	"$RRH_USR_BIN/rrh-doas" "$CONFIG_USER" /etc/rrh/cmd/update "$@" 2>&1 | tee "$CMD_OUTPUT_FILE"
-	UPDATE_EXIT_CODE=$?
+    "$RRH_USR_BIN/rrh-doas" "$CONFIG_USER" /etc/rrh/cmd/update "$@" 2>&1 | tee "$CMD_OUTPUT_FILE"
+    UPDATE_EXIT_CODE=$?
 fi
 echo "$UPDATE_EXIT_CODE" >"$EXIT_CODE_FILE"
 
 if [ -t 0 ]; then
-	IFS=';' read -sdR -p $'\E[6n' ROW COL # Get cursor position
-	[ $COL -ne 1 ] && echo '' # Add newline if cursor is not at 1st column
+    IFS=';' read -sdR -p $'\E[6n' ROW COL # Get cursor position
+    [ $COL -ne 1 ] && echo '' # Add newline if cursor is not at 1st column
 fi
 
 # write update time even if update fail
 echo "$(date -u +'%s')" >"$RRH_VAR/last_time"
 if [ ! $? -eq 0 ]; then
-	echo "write last update time failed!" >&2
-	exec 200>&-
-	rm /run/rrh.lck
-	exit 7
+    echo "write last update time failed!" >&2
+    exec 200>&-
+    rm /run/rrh.lck
+    exit 7
 fi
 echo "$ACTION_ID" >"$RRH_VAR/last"
 if [ ! $? -eq 0 ]; then
-	echo "write last update action id failed!" >&2
-	exec 200>&-
-	rm /run/rrh.lck
-	exit 7
+    echo "write last update action id failed!" >&2
+    exec 200>&-
+    rm /run/rrh.lck
+    exit 7
 fi
 
 if [ ! $UPDATE_EXIT_CODE -eq 0 ]; then
-	echo "update cmd failed(code $UPDATE_EXIT_CODE)!" >&2
-	exec 200>&-
-	rm /run/rrh.lck
-	exit 6
+    echo "update cmd failed(code $UPDATE_EXIT_CODE)!" >&2
+    exec 200>&-
+    rm /run/rrh.lck
+    exit 6
 fi
 
 if [ -f /etc/rrh/cmd/post_update ]; then
-	/etc/rrh/cmd/post_update
-	POST_UPDATE_CODE=$?
-	if [ ! $POST_UPDATE_CODE -eq 0 ]; then
-		echo "post_update cmd failed(code $POST_UPDATE_CODE)!"
-		exec 200>&-
-		rm /run/rrh.lck
-		exit 14
-	fi
+    /etc/rrh/cmd/post_update
+    POST_UPDATE_CODE=$?
+    if [ ! $POST_UPDATE_CODE -eq 0 ]; then
+        echo "post_update cmd failed(code $POST_UPDATE_CODE)!"
+        exec 200>&-
+        rm /run/rrh.lck
+        exit 14
+    fi
 fi
 
 if [ -f /etc/rrh/auto_digest ]; then
-	"$RRH_USR_BIN/rrh-output-digest" "$CMD_OUTPUT_FILE"
-	DIGEST_CODE=$?
-	if [ ! $DIGEST_CODE -eq 0 ]; then
-		echo "rrh-output-digest failed(code $DIGEST_CODE)!"
-		exec 200>&-
-		rm /run/rrh.lck
-		exit 16
-	fi
+    "$RRH_USR_BIN/rrh-output-digest" "$CMD_OUTPUT_FILE"
+    DIGEST_CODE=$?
+    if [ ! $DIGEST_CODE -eq 0 ]; then
+        echo "rrh-output-digest failed(code $DIGEST_CODE)!"
+        exec 200>&-
+        rm /run/rrh.lck
+        exit 16
+    fi
 fi
 
 if [ ! -f /etc/rrh/cmd/no_auto_remove ]; then
-	"$RRH_USR_BIN/rrh-auto-remove"
-	AUTO_REMOVE_CODE=$?
-	if [ ! $AUTO_REMOVE_CODE -eq 0 ]; then
-		echo "rrh-auto-remove failed(code $AUTO_REMOVE_CODE)!"
-		exec 200>&-
-		rm /run/rrh.lck
-		exit 17
-	fi
+    "$RRH_USR_BIN/rrh-auto-remove"
+    AUTO_REMOVE_CODE=$?
+    if [ ! $AUTO_REMOVE_CODE -eq 0 ]; then
+        echo "rrh-auto-remove failed(code $AUTO_REMOVE_CODE)!"
+        exec 200>&-
+        rm /run/rrh.lck
+        exit 17
+    fi
 fi
 
 exec 200>&-
diff --git a/src/bin/rrh-mark-update b/src/bin/rrh-mark-update
--- a/src/bin/rrh-mark-update
+++ b/src/bin/rrh-mark-update
@@ -6,10 +6,10 @@ RRH_USR_BIN="."
 RRH_VAR="$HOME/.cache/rrh-test"
 
 if [ ! "$#" -eq 0 ]; then
-	echo "Usage: rrh-mark-update"
+    echo "Usage: rrh-mark-update"
         echo "Mark once update. May require root."
-	echo "RRH $RRH_VERSION"
-	exit 8
+    echo "RRH $RRH_VERSION"
+    exit 8
 fi
 
 if [ "$(id -un)" != "root" ]; then
@@ -23,7 +23,7 @@ fi
 
 echo "$(date -u +'%s')" >"$RRH_VAR/last_time"
 if [ ! $? -eq 0 ]; then
-	echo "write last update time failed!" >&2
-	exit 7
+    echo "write last update time failed!" >&2
+    exit 7
 fi
 exit 0
